# Generated by Django 4.0.3 on 2022-04-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileObject',
            fields=[
                ('id', models.TextField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
    ]
