# Generated by Django 4.0.3 on 2022-04-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embededobject',
            name='filename',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='fileobject',
            name='filename',
            field=models.CharField(max_length=120),
        ),
    ]
